version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - food-delivery-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - food-delivery-network

  admin:
    build:
      context: ./admin
    ports:
      - "5174:5174"
    env_file:
      - ./admin/.env
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge
